version: '3'

services:
  autoparts:
    container_name: autoparts-app
    image: autoparts:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - autoparts-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://autoparts-db:5432/autoparts_ap
      - SPRING_DATASOURCE_USERNAME=postgres_AP_user
      - SPRING_DATASOURCE_PASSWORD=postgres_AP_pwd
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - CONFIG_LOCATION=file:/src/main/resources/application-ap.yaml
    ports:
      - 8080:8080
    restart: always
    networks:
      - "spring-cloud-network"

  autoparts-db:
    image: postgres:14-alpine
    container_name: autoparts-db
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres_AP_user
      POSTGRES_PASSWORD: postgres_AP_pwd
      POSTGRES_DB: autoparts_ap
      POSTGRES_DATABASE: autoparts_ap
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - "spring-cloud-network"

networks:
  spring-cloud-network:
    driver: bridge
