spring:
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/autoparts_ap
    username: postgres_AP_user
    password: postgres_AP_pwd

  liquibase:
    change-log: autoparts-ap-db-postgres.yaml

  jpa:
    hibernate:
      ddl-auto: create

autodoc-auth:
  username: user
  password: pwd

autoparts:
  sites:
    autodoc:
      enabled: true
      auth:
        username: usr
        password: pwd
    exist:
      enabled: false
    auth:
      username: usr
      password: pwd